pull_request_rules:
  - name: Keep generated catalog PRs up to date
    conditions:
      - base=main
      - head~=^automation/catalog-sync-
      - label=automation
      - label=catalog-update
      - label=spotify
    actions:
      update:
  - name: Keep Dependabot pull requests up to date
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - base=main
    actions:
      update:
