pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
  - name: Automatic merge on approval
    conditions:
      - author~=^javiyt$
    actions:
      merge:
        method: squash
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: squash
